name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate .env
        run: |
          echo "LarkAppId= ${{ secrets.LARKAPPID }} " > .env
          echo "LarkAppSecret= ${{ secrets.LARKAPPSECRET }} " >> .env
          echo "VerificationToken= ${{ secrets.VERIFICATIONTOKEN }} " >> .env
          echo "EncryptKey= ${{ secrets.ENCRYPTKEY }} " >> .env
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ospp-cr-bot"
          heroku_email: "me@lyle.net.cn"
          usedocker: true
